fix: Save file as readonly
linuxdeepin/deepin-ai-daemon pull request #62
Opened 2024-06-25 05:16 UTC by N0rthHXD

Save file as readonly.

Log:
Task: https://pms.uniontech.com/bug-view-259875.html

2024-06-27 03:16 UTC, Clauszy requested changes

2024-06-27 03:16 UTC, Clauszy commented on src/index/vectorindex/embedding.cpp
> +    process.start(cpCmd);
使用带参数的接口，不要直接用字符串写完整命令

2024-06-27 03:28 UTC, N0rthHXD commented on src/index/vectorindex/embedding.cpp
> +    process.start(cpCmd);
done

2024-07-01 08:33 UTC, Clauszy approved these changes

2024-07-01 08:33 UTC, N0rthHXD commented
/merge

2024-07-01 08:34 UTC, merged